# Generated by Django 5.2.4 on 2025-08-03 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_tripschedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tripschedule',
            name='notes',
        ),
        migrations.AddField(
            model_name='tripschedule',
            name='driver',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='tripschedule',
            name='driver_contact',
            field=models.CharField(default='0000000000', max_length=20),
        ),
    ]
