# Generated by Django 5.2.4 on 2025-08-03 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_remove_tripschedule_notes_tripschedule_driver_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisteredDriver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='drivers/')),
            ],
        ),
    ]
