# Generated by Django 5.2.6 on 2025-09-28 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver_Table',
            fields=[
                ('driver_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('contact_number', models.CharField(max_length=15, unique=True)),
                ('address', models.TextField()),
                ('license_number', models.CharField(max_length=20, unique=True)),
                ('license_expiry', models.DateField()),
                ('authority_to_drive', models.BooleanField(default=False)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='drivers/photos/')),
                ('date_registered', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle_Table',
            fields=[
                ('vehicle_id', models.AutoField(primary_key=True, serialize=False)),
                ('vehicle_type', models.CharField(choices=[('Bus', 'Bus'), ('Van', 'Van'), ('Car', 'Car'), ('Truck', 'Truck'), ('Jeepney', 'Jeepney'), ('Other', 'Other')], default='Bus', max_length=50)),
                ('vehicle_name', models.CharField(max_length=20, unique=True)),
                ('plate_number', models.CharField(max_length=20, unique=True)),
                ('manufacturer', models.CharField(blank=True, max_length=100, null=True)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('seat_capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('registration_number', models.CharField(max_length=50, unique=True)),
                ('registration_expiry', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('date_registered', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trip_Table',
            fields=[
                ('trip_id', models.AutoField(primary_key=True, serialize=False)),
                ('trip_name', models.CharField(max_length=100)),
                ('origin', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('departure_time', models.DateTimeField(help_text='Enter the exact departure date and time')),
                ('driver_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver_trips', to='ticket_models.driver_table')),
                ('vehicle_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_trips', to='ticket_models.vehicle_table')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket_Table',
            fields=[
                ('ticket_id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('tickets_quantity', models.IntegerField(default=0)),
                ('trip_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='ticket_models.trip_table')),
            ],
        ),
    ]
