# Generated by Django 5.2.6 on 2025-09-12 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_models', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip_Table',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('trip_name', models.CharField(max_length=100)),
                ('origin', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='ticket_table',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
