# Generated by Django 5.2.6 on 2025-09-12 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_models', '0002_trip_table_alter_ticket_table_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket_table',
            old_name='id',
            new_name='ticket_id',
        ),
        migrations.RenameField(
            model_name='trip_table',
            old_name='id',
            new_name='trip_id',
        ),
    ]
