# Generated by Django 5.2.6 on 2025-09-12 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_models', '0003_rename_id_ticket_table_ticket_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket_table',
            name='trip_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='ticket_models.trip_table'),
        ),
    ]
