# Generated by Django 5.2.6 on 2025-09-12 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_models', '0004_ticket_table_trip_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket_table',
            name='tickets_qty',
            field=models.IntegerField(default=0),
        ),
    ]
