# Generated by Django 5.2.6 on 2025-10-04 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_models', '0002_bookings_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings_table',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
