# Generated by Django 5.2.5 on 2025-08-31 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='password_dupli',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
