# Generated by Django 5.2.4 on 2025-07-03 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DriverInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('vehicle_type', models.CharField(max_length=50)),
                ('plate_number', models.CharField(max_length=20)),
                ('route_taken', models.CharField(max_length=200)),
            ],
        ),
    ]
