# Generated by Django 5.2.4 on 2025-08-03 03:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DriverInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('vehicle_type', models.CharField(max_length=50)),
                ('plate_number', models.CharField(max_length=20, unique=True)),
                ('route_taken', models.CharField(max_length=200)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qrapp/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver_image', models.ImageField(blank=True, null=True, upload_to='driver_images/')),
            ],
        ),
        migrations.CreateModel(
            name='DriverQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('departure_time', models.DateTimeField()),
                ('is_done', models.BooleanField(default=False)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qrapp.driverinfo')),
            ],
            options={
                'ordering': ['departure_time'],
            },
        ),
    ]
