# Generated by Django 5.2.4 on 2025-07-07 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qrapp', '0002_driverinfo_created_at_alter_driverinfo_plate_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='driverqueue',
            options={'ordering': ['scanned_at']},
        ),
        migrations.RemoveField(
            model_name='driverqueue',
            name='status',
        ),
    ]
