# Generated by Django 5.2.4 on 2025-07-07 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrapp', '0003_alter_driverqueue_options_remove_driverqueue_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverqueue',
            name='departure_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driverqueue',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
