# Generated by Django 5.2.4 on 2025-07-07 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrapp', '0005_alter_driverqueue_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverinfo',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
    ]
